// Root file for execution-specs tests
// This imports all generated state test files
// Auto-generated by scripts/update_spec_root.py

const std = @import("std");
const testing = std.testing;

// Re-export runner for generated tests
pub const runner = @import("runner.zig");

// Infrastructure test
test "spec runner infrastructure" {
    try testing.expect(true);
}

// Import generated state tests
